spring:

  datasource:
    url: jdbc:mysql://localhost:3360/db-it-center?createDatabaseIfNotExist=true
    username: root
    password:

#  datasource:
#    url: jdbc:h2:mem:it-center
#    username: sa
#    password: ""
#    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

application:
  security:
    jwt:
      secretKey: de6aaeabadeccc598160172044da9c566242ae3bde6aaeabadeccc598160172044da9c566242ae3b
      tokenValidityMilliseconds: 86400000
      rememberMeTokenValiditySeconds: 25920000000
    refreshToken:
      tokenValidityMilliseconds: 259200000

